/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b86ae5b9-243a-451d-8b4b-e00380f291e1",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XGRUvYxUF",
    "aws_user_pools_web_client_id": "6ud2gvkg4gmipbvts6knn6roh8",
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://ilw5lczvpvb25mcgd5ymbx6aam.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bfxhgefpyvdftd2p3g54gchmv4"

};

//'us-west-2:1626ac27-e83c-43a4-8314-5305071c9cac',

export default awsmobile;



//////////////// second attempt
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",

    "aws_appsync_graphqlEndpoint": "https://xwboqbuhzveixgrt4i7fv7kilu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    Auth: {
        identityPoolId: "us-west-2:b86ae5b9-243a-451d-8b4b-e00380f291e1",
        region: "us-west-2",
        userPoolId: "us-west-2_5XcNBhyk0",
        userPoolWebClientId: "6al44lcmgufr7mk38rb7a5uudj",
    },
    API: {
        endpoints: [
            {
                name: "CMAGuestAPI",
                endpoint: "https://d5d92ay1m1.execute-api.us-west-1.amazonaws.com/dev-auth/cma"
            }
        ]
    }

};

//'us-west-2:1626ac27-e83c-43a4-8314-5305071c9cac',

export default awsmobile;



